openapi: 3.1.0
info:
  version: 1.0.0
  title: RESTful API documentation for managing contacts and authentication
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of contacts app

tags:
  - name: Contacts
    description: Operations related to contact management
  - name: Auth
    description: Operations related to user authentication

servers:
  - url: https://nodejs-hw-mongodb-hw3-crud-9qln.onrender.com

security:
  - bearerAuth: []

paths:
  /contacts/{id}:
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml

  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml

  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml

  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml

  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml

  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/send-reset-email.yaml

  /auth/reset-pwd:
    post:
      $ref: ../swagger/paths/auth/reset-pwd.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    contact:
      $ref: ../swagger/components/schemas/contact.yaml
    loginResponse:
      $ref: ../swagger/components/schemas/loginResponse.yaml
    register:
      $ref: ../swagger/components/schemas/register.yaml
    resetPassword:
      $ref: ../swagger/components/schemas/resetPassword.yaml
    tokenResponse:
      $ref: ../swagger/components/schemas/tokenResponse.yaml
    userResponse:
      $ref: ../swagger/components/schemas/userResponse.yaml
